// <auto-generated />
using System;
using BelajarEntityFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BelajarEntityFramework.Migrations
{
    [DbContext(typeof(EFDbContext))]
    [Migration("20251209024538_UserProfileMig")]
    partial class UserProfileMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BelajarEntityFramework.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.IdentityProof", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProofTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<int>("VerificationStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProofTypeId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("VerificationStatusId");

                    b.ToTable("IdentityProofs");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("MainImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MainImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Brand = "AlphaTech",
                            Description = "A smart and stylish watch from AlphaTech.",
                            Discount = 5m,
                            Name = "Alpha Watch",
                            Price = 199.99m
                        },
                        new
                        {
                            ProductId = 2,
                            Brand = "AlphaTech",
                            Description = "A high-performance mobile device by AlphaTech.",
                            Discount = 10m,
                            Name = "Alpha Mobile",
                            Price = 499.99m
                        },
                        new
                        {
                            ProductId = 3,
                            Brand = "AlphaTech",
                            Description = "A lightweight and powerful laptop from AlphaTech.",
                            Discount = 15m,
                            Name = "Alpha Laptop",
                            Price = 999.99m
                        },
                        new
                        {
                            ProductId = 4,
                            Brand = "BetaWorks",
                            Description = "An elegant watch featuring modern functionalities by BetaWorks.",
                            Discount = 5m,
                            Name = "Beta Watch",
                            Price = 149.99m
                        },
                        new
                        {
                            ProductId = 5,
                            Brand = "BetaWorks",
                            Description = "An advanced mobile device with cutting-edge technology from BetaWorks.",
                            Discount = 10m,
                            Name = "Beta Mobile",
                            Price = 599.99m
                        },
                        new
                        {
                            ProductId = 6,
                            Brand = "BetaWorks",
                            Description = "A powerful laptop built for both gaming and professional use by BetaWorks.",
                            Discount = 20m,
                            Name = "Beta Laptop",
                            Price = 1099.99m
                        },
                        new
                        {
                            ProductId = 7,
                            Brand = "GammaCorp",
                            Description = "A sporty watch with fitness tracking features from GammaCorp.",
                            Discount = 5m,
                            Name = "Gamma Watch",
                            Price = 129.99m
                        },
                        new
                        {
                            ProductId = 8,
                            Brand = "GammaCorp",
                            Description = "A compact mobile device with excellent battery life by GammaCorp.",
                            Discount = 5m,
                            Name = "Gamma Mobile",
                            Price = 399.99m
                        },
                        new
                        {
                            ProductId = 9,
                            Brand = "GammaCorp",
                            Description = "A versatile laptop with long-lasting battery performance from GammaCorp.",
                            Discount = 10m,
                            Name = "Gamma Laptop",
                            Price = 899.99m
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.ProductImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.ProofType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProofTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Passport"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Driver License"
                        },
                        new
                        {
                            Id = 3,
                            Name = "National ID"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Voter ID"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Aadhar"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Pan"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProfilePictureFileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ProfilePictureFileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.VerificationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VerificationStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Verified"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rejected"
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Employee", b =>
                {
                    b.HasOne("BelajarEntityFramework.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.IdentityProof", b =>
                {
                    b.HasOne("BelajarEntityFramework.Models.ProofType", "ProofType")
                        .WithMany()
                        .HasForeignKey("ProofTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelajarEntityFramework.Models.UserProfile", "UserProfile")
                        .WithMany("IdentityProofs")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelajarEntityFramework.Models.VerificationStatus", "VerificationStatus")
                        .WithMany()
                        .HasForeignKey("VerificationStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProofType");

                    b.Navigation("UserProfile");

                    b.Navigation("VerificationStatus");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.ProductImage", b =>
                {
                    b.HasOne("BelajarEntityFramework.Models.Product", "Product")
                        .WithMany("RelatedImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Product", b =>
                {
                    b.Navigation("RelatedImages");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.UserProfile", b =>
                {
                    b.Navigation("IdentityProofs");
                });
#pragma warning restore 612, 618
        }
    }
}
