// <auto-generated />
using System;
using BelajarEntityFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BelajarEntityFramework.Migrations
{
    [DbContext(typeof(EFDbContext))]
    [Migration("20251215071217_ChartMig")]
    partial class ChartMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BelajarEntityFramework.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.HasKey("AttendanceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            AttendanceId = 1,
                            Date = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 1,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 2,
                            Date = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 1,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 3,
                            Date = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 2,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 4,
                            Date = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 2,
                            IsPresent = false
                        },
                        new
                        {
                            AttendanceId = 5,
                            Date = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 3,
                            IsPresent = false
                        },
                        new
                        {
                            AttendanceId = 6,
                            Date = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 3,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 7,
                            Date = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 4,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 8,
                            Date = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 4,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 9,
                            Date = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 5,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 10,
                            Date = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 5,
                            IsPresent = false
                        },
                        new
                        {
                            AttendanceId = 11,
                            Date = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 6,
                            IsPresent = false
                        },
                        new
                        {
                            AttendanceId = 12,
                            Date = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 6,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 13,
                            Date = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 7,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 14,
                            Date = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 7,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 15,
                            Date = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 8,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 16,
                            Date = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 8,
                            IsPresent = false
                        },
                        new
                        {
                            AttendanceId = 17,
                            Date = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 9,
                            IsPresent = false
                        },
                        new
                        {
                            AttendanceId = 18,
                            Date = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 9,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 19,
                            Date = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 10,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 20,
                            Date = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 10,
                            IsPresent = true
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Electronic gadgets and devices",
                            Name = "Electronics"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Clothing and fashion accessories",
                            Name = "Apparel"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Furniture and home decor",
                            Name = "Home Goods"
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "123 Main St, City A",
                            Email = "alice@example.com",
                            Name = "Alice Johnson",
                            Phone = "555-1234"
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "456 Elm St, City B",
                            Email = "bob@example.com",
                            Name = "Bob Smith",
                            Phone = "555-5678"
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.CustomerChart", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustomerId");

                    b.ToTable("CustomersChart");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Email = "alice@example.com",
                            Name = "Alice"
                        },
                        new
                        {
                            CustomerId = 2,
                            Email = "bob@example.com",
                            Name = "Bob"
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.DepartmentExcel", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("DepartmentsExcel");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            Name = "HR"
                        },
                        new
                        {
                            DepartmentId = 2,
                            Name = "Finance"
                        },
                        new
                        {
                            DepartmentId = 3,
                            Name = "IT"
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeTypeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.EmployeeExcel", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeTypeId");

                    b.ToTable("EmployeesExcel");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DepartmentId = 1,
                            Email = "john.doe@example.com",
                            EmployeeTypeId = 1,
                            FirstName = "John",
                            IsActive = true,
                            JoinDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Doe",
                            Salary = 60000m
                        },
                        new
                        {
                            EmployeeId = 2,
                            DepartmentId = 2,
                            Email = "jane.smith@example.com",
                            EmployeeTypeId = 2,
                            FirstName = "Jane",
                            IsActive = true,
                            JoinDate = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Smith",
                            Salary = 40000m
                        },
                        new
                        {
                            EmployeeId = 3,
                            DepartmentId = 3,
                            Email = "bob.johnson@example.com",
                            EmployeeTypeId = 3,
                            FirstName = "Bob",
                            IsActive = false,
                            JoinDate = new DateTime(2022, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Johnson",
                            Salary = 50000m
                        },
                        new
                        {
                            EmployeeId = 4,
                            DepartmentId = 1,
                            Email = "alice.williams@example.com",
                            EmployeeTypeId = 1,
                            FirstName = "Alice",
                            IsActive = true,
                            JoinDate = new DateTime(2019, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Williams",
                            Salary = 65000m
                        },
                        new
                        {
                            EmployeeId = 5,
                            DepartmentId = 2,
                            Email = "michael.brown@example.com",
                            EmployeeTypeId = 2,
                            FirstName = "Michael",
                            IsActive = true,
                            JoinDate = new DateTime(2018, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brown",
                            Salary = 55000m
                        },
                        new
                        {
                            EmployeeId = 6,
                            DepartmentId = 3,
                            Email = "linda.davis@example.com",
                            EmployeeTypeId = 3,
                            FirstName = "Linda",
                            IsActive = false,
                            JoinDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Davis",
                            Salary = 48000m
                        },
                        new
                        {
                            EmployeeId = 7,
                            DepartmentId = 1,
                            Email = "david.miller@example.com",
                            EmployeeTypeId = 1,
                            FirstName = "David",
                            IsActive = true,
                            JoinDate = new DateTime(2020, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Miller",
                            Salary = 62000m
                        },
                        new
                        {
                            EmployeeId = 8,
                            DepartmentId = 2,
                            Email = "susan.wilson@example.com",
                            EmployeeTypeId = 2,
                            FirstName = "Susan",
                            IsActive = true,
                            JoinDate = new DateTime(2021, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wilson",
                            Salary = 43000m
                        },
                        new
                        {
                            EmployeeId = 9,
                            DepartmentId = 3,
                            Email = "robert.moore@example.com",
                            EmployeeTypeId = 3,
                            FirstName = "Robert",
                            IsActive = false,
                            JoinDate = new DateTime(2022, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Moore",
                            Salary = 51000m
                        },
                        new
                        {
                            EmployeeId = 10,
                            DepartmentId = 1,
                            Email = "karen.taylor@example.com",
                            EmployeeTypeId = 1,
                            FirstName = "Karen",
                            IsActive = true,
                            JoinDate = new DateTime(2019, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Taylor",
                            Salary = 70000m
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.EmployeeType", b =>
                {
                    b.Property<int>("EmployeeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeTypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeTypeId");

                    b.ToTable("EmployeeTypes");

                    b.HasData(
                        new
                        {
                            EmployeeTypeId = 1,
                            TypeName = "Full Time"
                        },
                        new
                        {
                            EmployeeTypeId = 2,
                            TypeName = "Part Time"
                        },
                        new
                        {
                            EmployeeTypeId = 3,
                            TypeName = "Contractor"
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.IdentityProof", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProofTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<int>("VerificationStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProofTypeId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("VerificationStatusId");

                    b.ToTable("IdentityProofs");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalTax")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            GrandTotal = 1650.00m,
                            OrderDate = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderNumber = "ORD1001",
                            SubTotal = 1500.00m,
                            TotalTax = 150.00m
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 2,
                            GrandTotal = 880.00m,
                            OrderDate = new DateTime(2025, 12, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderNumber = "ORD1002",
                            SubTotal = 800.00m,
                            TotalTax = 80.00m
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.OrderChart", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("OrdersChart");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderNumber = "ORD-0001",
                            OrderStatus = 2,
                            TotalAmount = 1300m
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderNumber = "ORD-0002",
                            OrderStatus = 1,
                            TotalAmount = 2200m
                        },
                        new
                        {
                            OrderId = 3,
                            CustomerId = 1,
                            OrderDate = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderNumber = "ORD-0003",
                            OrderStatus = 3,
                            TotalAmount = 500m
                        },
                        new
                        {
                            OrderId = 4,
                            CustomerId = 2,
                            OrderDate = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderNumber = "ORD-0004",
                            OrderStatus = 2,
                            TotalAmount = 1600m
                        },
                        new
                        {
                            OrderId = 5,
                            CustomerId = 1,
                            OrderDate = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderNumber = "ORD-0005",
                            OrderStatus = 1,
                            TotalAmount = 900m
                        },
                        new
                        {
                            OrderId = 6,
                            CustomerId = 2,
                            OrderDate = new DateTime(2025, 12, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderNumber = "ORD-0006",
                            OrderStatus = 2,
                            TotalAmount = 1800m
                        },
                        new
                        {
                            OrderId = 7,
                            CustomerId = 1,
                            OrderDate = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderNumber = "ORD-0007",
                            OrderStatus = 2,
                            TotalAmount = 1100m
                        },
                        new
                        {
                            OrderId = 8,
                            CustomerId = 2,
                            OrderDate = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderNumber = "ORD-0008",
                            OrderStatus = 3,
                            TotalAmount = 2500m
                        },
                        new
                        {
                            OrderId = 9,
                            CustomerId = 1,
                            OrderDate = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderNumber = "ORD-0009",
                            OrderStatus = 1,
                            TotalAmount = 1700m
                        },
                        new
                        {
                            OrderId = 10,
                            CustomerId = 2,
                            OrderDate = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderNumber = "ORD-0010",
                            OrderStatus = 2,
                            TotalAmount = 1400m
                        },
                        new
                        {
                            OrderId = 11,
                            CustomerId = 1,
                            OrderDate = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderNumber = "ORD-0011",
                            OrderStatus = 2,
                            TotalAmount = 2000m
                        },
                        new
                        {
                            OrderId = 12,
                            CustomerId = 2,
                            OrderDate = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderNumber = "ORD-0012",
                            OrderStatus = 1,
                            TotalAmount = 2100m
                        },
                        new
                        {
                            OrderId = 13,
                            CustomerId = 1,
                            OrderDate = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderNumber = "ORD-0013",
                            OrderStatus = 2,
                            TotalAmount = 1300m
                        },
                        new
                        {
                            OrderId = 14,
                            CustomerId = 2,
                            OrderDate = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderNumber = "ORD-0014",
                            OrderStatus = 3,
                            TotalAmount = 1900m
                        },
                        new
                        {
                            OrderId = 15,
                            CustomerId = 1,
                            OrderDate = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderNumber = "ORD-0015",
                            OrderStatus = 2,
                            TotalAmount = 1500m
                        },
                        new
                        {
                            OrderId = 16,
                            CustomerId = 1,
                            OrderDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderNumber = "ORD-0016",
                            OrderStatus = 1,
                            TotalAmount = 300m
                        },
                        new
                        {
                            OrderId = 17,
                            CustomerId = 2,
                            OrderDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderNumber = "ORD-0017",
                            OrderStatus = 2,
                            TotalAmount = 800m
                        },
                        new
                        {
                            OrderId = 18,
                            CustomerId = 1,
                            OrderDate = new DateTime(2025, 12, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            OrderNumber = "ORD-0018",
                            OrderStatus = 3,
                            TotalAmount = 150m
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TaxPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            OrderItemId = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            TaxPercent = 10.00m,
                            UnitPrice = 1200.00m
                        },
                        new
                        {
                            OrderItemId = 2,
                            OrderId = 1,
                            ProductId = 3,
                            Quantity = 2,
                            TaxPercent = 10.00m,
                            UnitPrice = 150.00m
                        },
                        new
                        {
                            OrderItemId = 3,
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = 1,
                            TaxPercent = 10.00m,
                            UnitPrice = 800.00m
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.OrderItemChart", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItemsChart");

                    b.HasData(
                        new
                        {
                            OrderItemId = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 1200m
                        },
                        new
                        {
                            OrderItemId = 2,
                            OrderId = 1,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 100m
                        },
                        new
                        {
                            OrderItemId = 3,
                            OrderId = 2,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 1200m
                        },
                        new
                        {
                            OrderItemId = 4,
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 1000m
                        },
                        new
                        {
                            OrderItemId = 5,
                            OrderId = 3,
                            ProductId = 3,
                            Quantity = 5,
                            UnitPrice = 100m
                        },
                        new
                        {
                            OrderItemId = 6,
                            OrderId = 4,
                            ProductId = 2,
                            Quantity = 2,
                            UnitPrice = 800m
                        },
                        new
                        {
                            OrderItemId = 7,
                            OrderId = 5,
                            ProductId = 3,
                            Quantity = 3,
                            UnitPrice = 300m
                        },
                        new
                        {
                            OrderItemId = 8,
                            OrderId = 6,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 1200m
                        },
                        new
                        {
                            OrderItemId = 9,
                            OrderId = 6,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 600m
                        },
                        new
                        {
                            OrderItemId = 10,
                            OrderId = 7,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 1100m
                        },
                        new
                        {
                            OrderItemId = 11,
                            OrderId = 8,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 2500m
                        },
                        new
                        {
                            OrderItemId = 12,
                            OrderId = 9,
                            ProductId = 3,
                            Quantity = 2,
                            UnitPrice = 850m
                        },
                        new
                        {
                            OrderItemId = 13,
                            OrderId = 10,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 1400m
                        },
                        new
                        {
                            OrderItemId = 14,
                            OrderId = 11,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 2000m
                        },
                        new
                        {
                            OrderItemId = 15,
                            OrderId = 12,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 2100m
                        },
                        new
                        {
                            OrderItemId = 16,
                            OrderId = 13,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 1300m
                        },
                        new
                        {
                            OrderItemId = 17,
                            OrderId = 14,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 1900m
                        },
                        new
                        {
                            OrderItemId = 18,
                            OrderId = 15,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 1500m
                        },
                        new
                        {
                            OrderItemId = 19,
                            OrderId = 16,
                            ProductId = 3,
                            Quantity = 3,
                            UnitPrice = 100m
                        },
                        new
                        {
                            OrderItemId = 20,
                            OrderId = 17,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 800m
                        },
                        new
                        {
                            OrderItemId = 21,
                            OrderId = 18,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 150m
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PaymentId");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            OrderId = 1,
                            PaymentAmount = 1650.00m,
                            PaymentDate = new DateTime(2025, 12, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            PaymentMethod = "Credit Card",
                            PaymentStatus = "Paid"
                        },
                        new
                        {
                            PaymentId = 2,
                            OrderId = 2,
                            PaymentAmount = 880.00m,
                            PaymentDate = new DateTime(2025, 12, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            PaymentMethod = "PayPal",
                            PaymentStatus = "Paid"
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("MainImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MainImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Brand = "AlphaTech",
                            Description = "A smart and stylish watch from AlphaTech.",
                            Discount = 5m,
                            Name = "Alpha Watch",
                            Price = 199.99m
                        },
                        new
                        {
                            ProductId = 2,
                            Brand = "AlphaTech",
                            Description = "A high-performance mobile device by AlphaTech.",
                            Discount = 10m,
                            Name = "Alpha Mobile",
                            Price = 499.99m
                        },
                        new
                        {
                            ProductId = 3,
                            Brand = "AlphaTech",
                            Description = "A lightweight and powerful laptop from AlphaTech.",
                            Discount = 15m,
                            Name = "Alpha Laptop",
                            Price = 999.99m
                        },
                        new
                        {
                            ProductId = 4,
                            Brand = "BetaWorks",
                            Description = "An elegant watch featuring modern functionalities by BetaWorks.",
                            Discount = 5m,
                            Name = "Beta Watch",
                            Price = 149.99m
                        },
                        new
                        {
                            ProductId = 5,
                            Brand = "BetaWorks",
                            Description = "An advanced mobile device with cutting-edge technology from BetaWorks.",
                            Discount = 10m,
                            Name = "Beta Mobile",
                            Price = 599.99m
                        },
                        new
                        {
                            ProductId = 6,
                            Brand = "BetaWorks",
                            Description = "A powerful laptop built for both gaming and professional use by BetaWorks.",
                            Discount = 20m,
                            Name = "Beta Laptop",
                            Price = 1099.99m
                        },
                        new
                        {
                            ProductId = 7,
                            Brand = "GammaCorp",
                            Description = "A sporty watch with fitness tracking features from GammaCorp.",
                            Discount = 5m,
                            Name = "Gamma Watch",
                            Price = 129.99m
                        },
                        new
                        {
                            ProductId = 8,
                            Brand = "GammaCorp",
                            Description = "A compact mobile device with excellent battery life by GammaCorp.",
                            Discount = 5m,
                            Name = "Gamma Mobile",
                            Price = 399.99m
                        },
                        new
                        {
                            ProductId = 9,
                            Brand = "GammaCorp",
                            Description = "A versatile laptop with long-lasting battery performance from GammaCorp.",
                            Discount = 10m,
                            Name = "Gamma Laptop",
                            Price = 899.99m
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.ProductChart", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("ProductsChart");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Category = "Electronics",
                            Name = "Laptop",
                            Price = 1200m,
                            StockQuantity = 10
                        },
                        new
                        {
                            ProductId = 2,
                            Category = "Electronics",
                            Name = "Phone",
                            Price = 800m,
                            StockQuantity = 15
                        },
                        new
                        {
                            ProductId = 3,
                            Category = "Accessories",
                            Name = "Headphones",
                            Price = 100m,
                            StockQuantity = 30
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.ProductExcel", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SupplierId");

                    b.ToTable("ProductsExcel");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Brand = "SoundMax",
                            CategoryId = 1,
                            Description = "Noise-cancelling over-ear headphones",
                            DiscountPercentage = 10m,
                            IsActive = true,
                            Name = "Wireless Headphones",
                            Price = 99.99m,
                            Quantity = 50,
                            SKU = "ELE-SOU-WIR-TEC-2025",
                            SupplierId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            Brand = "FashionCo",
                            CategoryId = 2,
                            Description = "100% cotton, trendy design",
                            DiscountPercentage = 5m,
                            IsActive = true,
                            Name = "Designer T-Shirt",
                            Price = 29.99m,
                            Quantity = 150,
                            SKU = "APP-FAS-DES-FAS-2025",
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 3,
                            Brand = "VisionTech",
                            CategoryId = 1,
                            Description = "50-inch 4K Ultra HD Smart LED TV",
                            DiscountPercentage = 15m,
                            IsActive = true,
                            Name = "Smart LED TV",
                            Price = 499.99m,
                            Quantity = 30,
                            SKU = "ELE-VIS-SMA-TEC-2025",
                            SupplierId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            Brand = "HomeComfort",
                            CategoryId = 3,
                            Description = "Comfortable 3-seater sofa",
                            DiscountPercentage = 8m,
                            IsActive = true,
                            Name = "Modern Sofa",
                            Price = 299.99m,
                            Quantity = 20,
                            SKU = "HOM-HOM-MOD-FAS-2025",
                            SupplierId = 2
                        },
                        new
                        {
                            ProductId = 5,
                            Brand = "SoundMax",
                            CategoryId = 1,
                            Description = "Portable wireless speaker with deep bass",
                            DiscountPercentage = 12m,
                            IsActive = true,
                            Name = "Bluetooth Speaker",
                            Price = 49.99m,
                            Quantity = 80,
                            SKU = "ELE-SOU-BLU-TEC-2025",
                            SupplierId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            Brand = "",
                            CategoryId = 2,
                            Description = "Comfortable and stylish sneakers",
                            DiscountPercentage = 0m,
                            IsActive = true,
                            Name = "Casual Sneakers",
                            Price = 59.99m,
                            Quantity = 100,
                            SKU = "APP-BRD-CAS-FAS-2025",
                            SupplierId = 2
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.ProductImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.ProductPdf", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("ProductsPdf");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Description = "High performance laptop",
                            Name = "Laptop",
                            Price = 1200.00m
                        },
                        new
                        {
                            ProductId = 2,
                            Description = "Latest model smartphone",
                            Name = "Smartphone",
                            Price = 800.00m
                        },
                        new
                        {
                            ProductId = 3,
                            Description = "Noise-cancelling headphones",
                            Name = "Headphones",
                            Price = 150.00m
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.ProofType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProofTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Passport"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Driver License"
                        },
                        new
                        {
                            Id = 3,
                            Name = "National ID"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Voter ID"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Aadhar"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Pan"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            ContactEmail = "contact@techsource.com",
                            Name = "TechSource",
                            PhoneNumber = "555-1234"
                        },
                        new
                        {
                            SupplierId = 2,
                            ContactEmail = "sales@fashionhub.com",
                            Name = "FashionHub",
                            PhoneNumber = "555-5678"
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProfilePictureFileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ProfilePictureFileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.VerificationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VerificationStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Verified"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rejected"
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Attendance", b =>
                {
                    b.HasOne("BelajarEntityFramework.Models.EmployeeExcel", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Employee", b =>
                {
                    b.HasOne("BelajarEntityFramework.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelajarEntityFramework.Models.EmployeeType", null)
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeTypeId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.EmployeeExcel", b =>
                {
                    b.HasOne("BelajarEntityFramework.Models.DepartmentExcel", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelajarEntityFramework.Models.EmployeeType", "EmployeeType")
                        .WithMany()
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("EmployeeType");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.IdentityProof", b =>
                {
                    b.HasOne("BelajarEntityFramework.Models.ProofType", "ProofType")
                        .WithMany()
                        .HasForeignKey("ProofTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelajarEntityFramework.Models.UserProfile", "UserProfile")
                        .WithMany("IdentityProofs")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelajarEntityFramework.Models.VerificationStatus", "VerificationStatus")
                        .WithMany()
                        .HasForeignKey("VerificationStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProofType");

                    b.Navigation("UserProfile");

                    b.Navigation("VerificationStatus");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Order", b =>
                {
                    b.HasOne("BelajarEntityFramework.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.OrderChart", b =>
                {
                    b.HasOne("BelajarEntityFramework.Models.CustomerChart", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.OrderItem", b =>
                {
                    b.HasOne("BelajarEntityFramework.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelajarEntityFramework.Models.ProductPdf", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.OrderItemChart", b =>
                {
                    b.HasOne("BelajarEntityFramework.Models.OrderChart", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelajarEntityFramework.Models.ProductChart", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Payment", b =>
                {
                    b.HasOne("BelajarEntityFramework.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("BelajarEntityFramework.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Product", b =>
                {
                    b.HasOne("BelajarEntityFramework.Models.Supplier", null)
                        .WithMany("Products")
                        .HasForeignKey("SupplierId");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.ProductExcel", b =>
                {
                    b.HasOne("BelajarEntityFramework.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelajarEntityFramework.Models.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.ProductImage", b =>
                {
                    b.HasOne("BelajarEntityFramework.Models.Product", "Product")
                        .WithMany("RelatedImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.CustomerChart", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.DepartmentExcel", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.EmployeeExcel", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.EmployeeType", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Payment")
                        .IsRequired();
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.OrderChart", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Product", b =>
                {
                    b.Navigation("RelatedImages");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.ProductPdf", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.UserProfile", b =>
                {
                    b.Navigation("IdentityProofs");
                });
#pragma warning restore 612, 618
        }
    }
}
