// <auto-generated />
using System;
using BelajarEntityFramework.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BelajarEntityFramework.Migrations
{
    [DbContext(typeof(EFDbContext))]
    [Migration("20251209035005_ExcelMig")]
    partial class ExcelMig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BelajarEntityFramework.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("bit");

                    b.HasKey("AttendanceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Attendances");

                    b.HasData(
                        new
                        {
                            AttendanceId = 1,
                            Date = new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 1,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 2,
                            Date = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 1,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 3,
                            Date = new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 2,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 4,
                            Date = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 2,
                            IsPresent = false
                        },
                        new
                        {
                            AttendanceId = 5,
                            Date = new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 3,
                            IsPresent = false
                        },
                        new
                        {
                            AttendanceId = 6,
                            Date = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 3,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 7,
                            Date = new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 4,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 8,
                            Date = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 4,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 9,
                            Date = new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 5,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 10,
                            Date = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 5,
                            IsPresent = false
                        },
                        new
                        {
                            AttendanceId = 11,
                            Date = new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 6,
                            IsPresent = false
                        },
                        new
                        {
                            AttendanceId = 12,
                            Date = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 6,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 13,
                            Date = new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 7,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 14,
                            Date = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 7,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 15,
                            Date = new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 8,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 16,
                            Date = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 8,
                            IsPresent = false
                        },
                        new
                        {
                            AttendanceId = 17,
                            Date = new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 9,
                            IsPresent = false
                        },
                        new
                        {
                            AttendanceId = 18,
                            Date = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 9,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 19,
                            Date = new DateTime(2025, 12, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 10,
                            IsPresent = true
                        },
                        new
                        {
                            AttendanceId = 20,
                            Date = new DateTime(2025, 12, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeId = 10,
                            IsPresent = true
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.DepartmentExcel", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("DepartmentsExcel");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            Name = "HR"
                        },
                        new
                        {
                            DepartmentId = 2,
                            Name = "Finance"
                        },
                        new
                        {
                            DepartmentId = 3,
                            Name = "IT"
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeTypeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.EmployeeExcel", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeTypeId");

                    b.ToTable("EmployeesExcel");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DepartmentId = 1,
                            Email = "john.doe@example.com",
                            EmployeeTypeId = 1,
                            FirstName = "John",
                            IsActive = true,
                            JoinDate = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Doe",
                            Salary = 60000m
                        },
                        new
                        {
                            EmployeeId = 2,
                            DepartmentId = 2,
                            Email = "jane.smith@example.com",
                            EmployeeTypeId = 2,
                            FirstName = "Jane",
                            IsActive = true,
                            JoinDate = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Smith",
                            Salary = 40000m
                        },
                        new
                        {
                            EmployeeId = 3,
                            DepartmentId = 3,
                            Email = "bob.johnson@example.com",
                            EmployeeTypeId = 3,
                            FirstName = "Bob",
                            IsActive = false,
                            JoinDate = new DateTime(2022, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Johnson",
                            Salary = 50000m
                        },
                        new
                        {
                            EmployeeId = 4,
                            DepartmentId = 1,
                            Email = "alice.williams@example.com",
                            EmployeeTypeId = 1,
                            FirstName = "Alice",
                            IsActive = true,
                            JoinDate = new DateTime(2019, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Williams",
                            Salary = 65000m
                        },
                        new
                        {
                            EmployeeId = 5,
                            DepartmentId = 2,
                            Email = "michael.brown@example.com",
                            EmployeeTypeId = 2,
                            FirstName = "Michael",
                            IsActive = true,
                            JoinDate = new DateTime(2018, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Brown",
                            Salary = 55000m
                        },
                        new
                        {
                            EmployeeId = 6,
                            DepartmentId = 3,
                            Email = "linda.davis@example.com",
                            EmployeeTypeId = 3,
                            FirstName = "Linda",
                            IsActive = false,
                            JoinDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Davis",
                            Salary = 48000m
                        },
                        new
                        {
                            EmployeeId = 7,
                            DepartmentId = 1,
                            Email = "david.miller@example.com",
                            EmployeeTypeId = 1,
                            FirstName = "David",
                            IsActive = true,
                            JoinDate = new DateTime(2020, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Miller",
                            Salary = 62000m
                        },
                        new
                        {
                            EmployeeId = 8,
                            DepartmentId = 2,
                            Email = "susan.wilson@example.com",
                            EmployeeTypeId = 2,
                            FirstName = "Susan",
                            IsActive = true,
                            JoinDate = new DateTime(2021, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Wilson",
                            Salary = 43000m
                        },
                        new
                        {
                            EmployeeId = 9,
                            DepartmentId = 3,
                            Email = "robert.moore@example.com",
                            EmployeeTypeId = 3,
                            FirstName = "Robert",
                            IsActive = false,
                            JoinDate = new DateTime(2022, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Moore",
                            Salary = 51000m
                        },
                        new
                        {
                            EmployeeId = 10,
                            DepartmentId = 1,
                            Email = "karen.taylor@example.com",
                            EmployeeTypeId = 1,
                            FirstName = "Karen",
                            IsActive = true,
                            JoinDate = new DateTime(2019, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastName = "Taylor",
                            Salary = 70000m
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.EmployeeType", b =>
                {
                    b.Property<int>("EmployeeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeTypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeTypeId");

                    b.ToTable("EmployeeTypes");

                    b.HasData(
                        new
                        {
                            EmployeeTypeId = 1,
                            TypeName = "Full Time"
                        },
                        new
                        {
                            EmployeeTypeId = 2,
                            TypeName = "Part Time"
                        },
                        new
                        {
                            EmployeeTypeId = 3,
                            TypeName = "Contractor"
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.IdentityProof", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdminComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProofTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<int>("VerificationStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProofTypeId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("VerificationStatusId");

                    b.ToTable("IdentityProofs");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("MainImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("MainImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Brand = "AlphaTech",
                            Description = "A smart and stylish watch from AlphaTech.",
                            Discount = 5m,
                            Name = "Alpha Watch",
                            Price = 199.99m
                        },
                        new
                        {
                            ProductId = 2,
                            Brand = "AlphaTech",
                            Description = "A high-performance mobile device by AlphaTech.",
                            Discount = 10m,
                            Name = "Alpha Mobile",
                            Price = 499.99m
                        },
                        new
                        {
                            ProductId = 3,
                            Brand = "AlphaTech",
                            Description = "A lightweight and powerful laptop from AlphaTech.",
                            Discount = 15m,
                            Name = "Alpha Laptop",
                            Price = 999.99m
                        },
                        new
                        {
                            ProductId = 4,
                            Brand = "BetaWorks",
                            Description = "An elegant watch featuring modern functionalities by BetaWorks.",
                            Discount = 5m,
                            Name = "Beta Watch",
                            Price = 149.99m
                        },
                        new
                        {
                            ProductId = 5,
                            Brand = "BetaWorks",
                            Description = "An advanced mobile device with cutting-edge technology from BetaWorks.",
                            Discount = 10m,
                            Name = "Beta Mobile",
                            Price = 599.99m
                        },
                        new
                        {
                            ProductId = 6,
                            Brand = "BetaWorks",
                            Description = "A powerful laptop built for both gaming and professional use by BetaWorks.",
                            Discount = 20m,
                            Name = "Beta Laptop",
                            Price = 1099.99m
                        },
                        new
                        {
                            ProductId = 7,
                            Brand = "GammaCorp",
                            Description = "A sporty watch with fitness tracking features from GammaCorp.",
                            Discount = 5m,
                            Name = "Gamma Watch",
                            Price = 129.99m
                        },
                        new
                        {
                            ProductId = 8,
                            Brand = "GammaCorp",
                            Description = "A compact mobile device with excellent battery life by GammaCorp.",
                            Discount = 5m,
                            Name = "Gamma Mobile",
                            Price = 399.99m
                        },
                        new
                        {
                            ProductId = 9,
                            Brand = "GammaCorp",
                            Description = "A versatile laptop with long-lasting battery performance from GammaCorp.",
                            Discount = 10m,
                            Name = "Gamma Laptop",
                            Price = 899.99m
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.ProductImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.ProofType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProofTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Passport"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Driver License"
                        },
                        new
                        {
                            Id = 3,
                            Name = "National ID"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Voter ID"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Aadhar"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Pan"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePictureFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ProfilePictureFileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("ProfilePictureFileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.VerificationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VerificationStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Verified"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rejected"
                        });
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Attendance", b =>
                {
                    b.HasOne("BelajarEntityFramework.Models.EmployeeExcel", "Employee")
                        .WithMany("Attendances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Employee", b =>
                {
                    b.HasOne("BelajarEntityFramework.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelajarEntityFramework.Models.EmployeeType", null)
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeTypeId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.EmployeeExcel", b =>
                {
                    b.HasOne("BelajarEntityFramework.Models.DepartmentExcel", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelajarEntityFramework.Models.EmployeeType", "EmployeeType")
                        .WithMany()
                        .HasForeignKey("EmployeeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("EmployeeType");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.IdentityProof", b =>
                {
                    b.HasOne("BelajarEntityFramework.Models.ProofType", "ProofType")
                        .WithMany()
                        .HasForeignKey("ProofTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelajarEntityFramework.Models.UserProfile", "UserProfile")
                        .WithMany("IdentityProofs")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelajarEntityFramework.Models.VerificationStatus", "VerificationStatus")
                        .WithMany()
                        .HasForeignKey("VerificationStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProofType");

                    b.Navigation("UserProfile");

                    b.Navigation("VerificationStatus");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.ProductImage", b =>
                {
                    b.HasOne("BelajarEntityFramework.Models.Product", "Product")
                        .WithMany("RelatedImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.DepartmentExcel", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.EmployeeExcel", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.EmployeeType", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.Product", b =>
                {
                    b.Navigation("RelatedImages");
                });

            modelBuilder.Entity("BelajarEntityFramework.Models.UserProfile", b =>
                {
                    b.Navigation("IdentityProofs");
                });
#pragma warning restore 612, 618
        }
    }
}
